project_id: '674302'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: 1
files:
  - source: /apps/docs/**/*
    translation: /apps/docs/%two_letters_code%/**/%original_file_name%
    ignore:
      - /apps/docs/public
      - /apps/docs/.vitepress/
      - /apps/docs/package.json
      - /apps/docs/vercel.json
      - /apps/docs/%two_letters_code%/
