export const ERR_AUTH_DATE_INVALID = 'ERR_AUTH_DATE_INVALID';
export const ERR_HASH_INVALID = 'ERR_HASH_INVALID';
export const ERR_EXPIRED = 'ERR_EXPIRED';
export const ERR_SIGN_INVALID = 'ERR_SIGN_INVALID';