export const ERR_INVALID_VALUE = 'ERR_INVALID_VALUE';
export const ERR_UNEXPECTED_VALUE = 'ERR_UNEXPECTED_VALUE';
export const ERR_UNEXPECTED_TYPE = 'ERR_UNEXPECTED_TYPE';
export const ERR_PARSE = 'ERR_PARSE';

export type ErrorType =
  | typeof ERR_PARSE
  | typeof ERR_UNEXPECTED_TYPE
  | typeof ERR_INVALID_VALUE
  | typeof ERR_UNEXPECTED_VALUE;
