export const ERR_METHOD_UNSUPPORTED = 'ERR_METHOD_UNSUPPORTED';
export const ERR_RETRIEVE_LP_FAILED = 'ERR_RETRIEVE_LP_FAILED';
export const ERR_METHOD_PARAMETER_UNSUPPORTED = 'ERR_METHOD_PARAMETER_UNSUPPORTED';
export const ERR_UNKNOWN_ENV = 'ERR_UNKNOWN_ENV';
export const ERR_INVOKE_CUSTOM_METHOD_RESPONSE = 'ERR_INVOKE_CUSTOM_METHOD_RESPONSE';
export const ERR_TIMED_OUT = 'ERR_TIMED_OUT';

export type ErrorType =
  | typeof ERR_METHOD_UNSUPPORTED
  | typeof ERR_RETRIEVE_LP_FAILED
  | typeof ERR_METHOD_PARAMETER_UNSUPPORTED
  | typeof ERR_UNKNOWN_ENV
  | typeof ERR_INVOKE_CUSTOM_METHOD_RESPONSE
  | typeof ERR_TIMED_OUT;
