export {
  isSupported,
  close,
  bindCssVars,
  mountError,
  isMounted,
  isMounting,
  mountPromise,
  mount,
  ready,
  unmount,
  setBottomBarColor,
  setHeaderColor,
  setBackgroundColor,
  mountSync,
} from './methods.js';
export {
  state,
  isDark,
  isCssVarsBound,
  backgroundColorRGB,
  headerColor,
  headerColorRGB,
  bottomBarColorRGB,
  backgroundColor,
  bottomBarColor,
  isActive,
} from './signals.js';
