//#region API

export const ERR_FETCH_FAILED = 'ERR_FETCH_FAILED';
export const ERR_RESPONSE_NOT_JSON = 'ERR_RESPONSE_NOT_JSON';
export const ERR_UNEXPECTED_RESPONSE = 'ERR_UNEXPECTED_RESPONSE';
export const ERR_RESPONSE_NOT_OK = 'ERR_RESPONSE_NOT_OK';

//#endregion

export const ERR_NOT_DIR = 'ERR_NOT_DIR';
export const ERR_CONFIG_NOT_FOUND = 'ERR_CONFIG_NOT_FOUND';
export const ERR_CONFIG_INVALID = 'ERR_CONFIG_INVALID';